services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build: ./api
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: on-failure

  web:
    build: ./web
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - api

volumes:
  db_data:

networks:
  app-network:
    driver: bridge